baseurl = "https://akinkara.dev"
#baseurl = "https://akinkara.github.io"
title = "Akin" # Kara
theme = "PaperMod"
languageCode = "en-us"
paginate = 5

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  [params.profileMode]
  enabled = false
  title = "ExampleSite"
  subtitle = "This is subtitle"
  imageUrl = "<img location>"
  imageWidth = 120
  imageHeight = 120
  imageTitle = "my image"

    [[params.profileMode.buttons]]
    name = "Posts"
    url = "posts"

    [[params.profileMode.buttons]]
    name = "Tags"
    url = "tags"

  [params.homeInfoParams]
  Title = "Hi 👋"
  Content = "Welcome to my blog"

  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/akinkara"

#   [[params.socialIcons]]
#   name = "twitter"
#   url = "https://twitter.com/AknKARA8"

  [[params.socialIcons]]
  name = "stackoverflow"
  url = "https://stackoverflow.com/users/10063701/akin"

#   [[params.socialIcons]]
#   name = "medium"
#   url = "https://medium.com/@akinkara5006"

  [[params.socialIcons]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/akinkara/"

  [[params.socialIcons]]
  name = "email"
  url = "mailto:akinkara5006@gmail.com"

  

  
